import type { Metadata } from "next";
import { Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { SidebarProvider } from "@/context/sidebar-context";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fintrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="font-sans flex gap-7 flex-col h-screen px-6 pb-6 sm:px-8 sm:pb-8 lg:px-12 lg:pb-12">
            <Header />

            <main className="flex flex-1 overflow-hidden">
              <Sidebar />

              <section className="flex-1 overflow-y-auto hide-scrollbar">
                {children}
              </section>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
